### ISSUE TITLE
Add list of issues up for grabs

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Issues.Website#129]
It would be nice to have a list of all issues, across all addins, which are up for grabs in the contributing sections

**Comment by DiDoHH** [comment]
Do I understand it right, that this issue is about having a list of all open issues with the label "up-for-grabs" of the cake "organization" on https://cakeissues.net/
If so: Do you want it generated dynamic per webpage request (i.e. JS) or static generated with the code of the webpage (i.e. during generation)?

**Comment by pascalberger** [comment]
Thanks for your interesting in this 👍. It should list up-for-grabs issues from repos in the `cake-contrib` organization with the topic `cake-issues` (https://github.com/search?q=topic%3Acake-issues&type=Repositories), not from the Cake organization.

Cakeissues.net is generated once a day, so implementing it during generation should be fine.

**Comment by DiDoHH** [comment]
Hello @pascalberger,
I just forked this project to try to work on it. It seems a little bit bigger than I can make, but I give it a try.
Unfortunately I'm not able to build the project. Do you have a hint, what I have to do to build it?
Best regards
Diana

**Comment by DiDoHH** [comment]
That was the information I missed `-target GetArtifacts`. Thanks! 👍
So, now official: I would like to work on this. 😉

- I can already read issues, but I'm not yet very happy with the presentation. 
Do you have an idea how to display the issues? In a list or in a table? If not, I'll provide you something and you can create new issues for another presentation 😄 
- Right now, there are no issues with the label "up-for-grabs". I use "help wanted" for development. But this, in the end, is just a little configuration.
- We have to talk about where / how to store the token for the GitHub-requests. Should I assume that the token is present in an environment variable.
- Do you have preferences where the list, table, whatever, should show up on the website? A new menu item or a page behind a new button on the startpage?!?

**Comment by pascalberger** [comment]
You can use `BuildParameters.Wyam.AccessToken` as token for reading the issues
